name: Test Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Ansible
        run: pip install ansible

      - name: Modify /etc/hosts
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: /etc/hosts
          body: "127.0.0.1 localhost"

      - name: Test Ansible Playbook on Ubuntu
        run: |
          ansible-playbook -i inventory.ini setup-system.yml 
          # Check if the user is a member of the sudo group
          ansible-playbook -i inventory.txt -m user.info -a 'username=my_user groups=sudo'
